services:
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        ports:
            - "9876:13500"
        environment:
            # Spring Bootの設定を環境変数で上書き (PostgreSQLへの接続設定)
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/teamsurveydb?stringtype=unspecified
            SPRING_DATASOURCE_USERNAME: teamsurveyuser
            SPRING_DATASOURCE_PASSWORD: teamsurveypass
            SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver

            SPRING_SQL_INIT_MODE: never
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:16
        environment:
            POSTGRES_DB: teamsurveydb
            POSTGRES_USER: teamsurveyuser
            POSTGRES_PASSWORD: teamsurveypass
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql
            - ./docker/db:/docker-entrypoint-initdb.d # 初期化用SQL読み込み設定
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U teamsurveyuser -d teamsurveydb"]
            interval: 2s
            timeout: 10s
            retries: 5

volumes:
    db_data:
