
# code-server環境用
spring.datasource.url=jdbc:postgresql://db:5432/codeserverdb
spring.datasource.username=codeservertest
spring.datasource.password=codeserverpass
spring.datasource.driver-class-name=org.postgresql.Driver
app.proxy.prefix=/proxy/13500
spring.sql.init.mode=always
#logging.level.com.example.webapp.repository=DEBUG